---
version:  2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          PGHOST: localhost
          PGUSER: bekirinan
          RAILS_ENV: test
      - image: postgres:11
        environment:
          POSTGRES_USER:  bekirinan
          POSTGRES_DB:  sporavarim-backend-rubyonrails_test
          POSTGRES_PASSWORD:  ""
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        environment:
        - cluster.name: elasticsearch
        - xpack.security.enabled: false
        - transport.host: localhost
        - network.host: 127.0.0.1
        - http.port: 9200
        - discovery.type: single-node
    steps:
      - checkout

      - run:
          name: Installing bundles
          command: bundle install

      - run:
          name: Database setup
          command: bundle exec rake db:setup

      - run:
          command: bundle exec rake db:seed

      # Run the tests
      - run:  
          name: Run the tests
          command: bundle exec rspec spec