---
version:  2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        environment:
        - cluster.name: elasticsearch
        - xpack.security.enabled: false
        - transport.host: localhost
        - network.host: 127.0.0.1
        - http.port: 9200
        - discovery.type: single-node
    steps:
      - checkout

      - run:
          name: Installing bundles
          command: bundle install

      # Run the tests
      - run:  
          name: Run the tests
          command: bundle exec rspec spec